name: Build Docker

on:
  workflow_call:
    inputs:
      push_image:
        type: boolean
        required: false
        default: true

jobs:
  build:
    runs-on: 'ubuntu-latest'
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: ${{ inputs.push_image }}
        tags: ghcr.io/${{ github.repository }}:latest
